language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy3"
install:
    - pip install py>=1.5.0
    - pip install pytest>=3.1.2, pytest-cov>=2.2.1, mock>=2.0.0
    - pip install coveralls
    - pip install pylint
    - pip install pep8
script:
    - if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]]; then pylint --rcfile=.pylintrc pysm && pep8 pysm && python setup.py test ; fi
sudo: false
after_success:
  coveralls
