language: python
python:
  - "2.7"
  - "2.6"
install:
    - pip install pytest>=2.9.1, pytest-cov>=2.2.1, mock>=2.0.0
    - pip install coveralls
script:  python setup.py test
sudo: false
after_success:
  coveralls
