language: python
python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
install:
    - pip install pytest>=2.9.1, pytest-cov>=2.2.1, mock>=2.0.0
    - pip install coveralls
    - pip install pylint
    - pip install pep8
script:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.6" ]]; then pep8 pysm && python setup.py test ; fi
    - if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]]; then pylint --rcfile=.pylintrc pysm && pep8 pysm && python setup.py test ; fi
sudo: false
after_success:
  coveralls
